feat: add MilvusIndexer (#1)
* feat: add milvus indexer

Signed-off-by: anna-charlotte <charlotte.gerhaher@jina.ai>
Co-authored-by: Johannes Messner <44071807+JohannesMessner@users.noreply.github.com>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -3,5 +3,100 @@ name: CI
 on: [pull_request]
 
 jobs:
-  call-external:
-    uses: jina-ai/workflows-executors/.github/workflows/ci.yml@master
+  tests:
+    strategy:
+      fail-fast: false
+      matrix:
+        test-path: [ 'tests/unit/test_executor.py', 'tests/integration/test_flow.py', 'tests/integration/test_filtering.py', 'tests/integration/test_reload_keep_state.py', 'tests/integration/test_replicas.py', 'tests/integration/test_replicas_reindex.py' ]
+    runs-on: ubuntu-latest
+    defaults:
+      run:
+        working-directory: .
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+      - uses: actions/setup-python@v2
+        with:
+          python-version: "3.7"
+      - name: Pre-test script
+        run: |
+          if [[ -f "tests/pre_test.sh" ]]; then
+            bash tests/pre_test.sh; fi
+      - name: Install latest stable 3.x jina version
+        run: |
+          pip install jina
+      - name: Python requirements
+        run: |
+          if [ -f requirements.txt ]; then
+            pip install -r requirements.txt ; fi
+          if [ -f tests/requirements.txt ]; then
+            pip install -r tests/requirements.txt ; fi
+      - name: Create Dockerfile, if needed
+        run: |
+          if [[ ! -f "Dockerfile" ]]; then
+            docker run --entrypoint="executor_manager" -v "$(pwd):/workspace" \
+            jinahub/hubble-normalizer:latest normalize . --jina-version=3
+            sudo chown -R $(id -u ${USER}):$(id -g ${USER}) . ; fi
+      - name: Run unit tests
+        run: |
+          python -m pytest -s -v -m "not gpu" ${{ matrix.test-path }}
+      - id: test_docker
+        name: run docker tests
+        run: |
+          #!/bin/bash
+          # find all the examples with changed code
+          # run the docker test in that directory
+          set -ex
+
+          test_dir=$1
+          echo testing $test_dir
+          cd $test_dir
+
+          # assume failure
+          local_exit_code=1
+
+          # test docker image actually runs
+          if [[ -f "Dockerfile" ]]; then
+            python -m venv .venv
+            source .venv/bin/activate
+            pip install wheel docker jina
+            if [[ -f "requirements.txt" ]]; then
+              pip install -r requirements.txt
+            fi
+
+            if [[ -f "tests/requirements.txt" ]]; then
+              pip install -r tests/requirements.txt
+            fi
+
+            docker build -t foo .
+            if [[ -f "tests/pre-docker.sh" ]]; then # allow entrypoint for any pre-docker run operations, liek downloading a model to mount
+              bash tests/pre-docker.sh
+            fi
+            if [[ -f "tests/docker_args.txt" ]]; then # allow args to be passed to the `jina pea`
+                ARGS=`cat tests/docker_args.txt`
+              else
+                ARGS=""
+            fi
+            nohup jina executor --uses docker://foo:latest $ARGS --name Foo > nohup.out 2>&1 &
+            PID=$!
+            sleep 10
+            if ps -p $PID > /dev/null;
+            then
+              kill -9 $PID
+              docker rm -f $(docker ps -a -q)
+              docker rmi foo:latest
+              local_exit_code=0
+            else
+              echo "jina executor --uses docker://foo:latest --name Foo" could NOT start
+            fi
+            echo ~~~~~~~OUTPUT BELOW~~~~~~~
+            cat nohup.out
+          else
+            echo no Dockerfile, nothing to test
+            local_exit_code=0
+          fi
+
+          echo final exit code = $local_exit_code
+          exit $local_exit_code
+      - run: echo test result ${{ steps.test_docker.outputs.exit_code}}
+        shell: bash
